package mypojos;
// Generated May 13, 2020 12:51:40 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FashionstockHasUser generated by hbm2java
 */
public class FashionstockHasUser  implements java.io.Serializable {


     private Integer fuelstockHasUserid;
     private Fashionstock fashionstock;
     private User user;
     private Date dateintake;
     private Double qtyintake;
     private Double suprate;
     private Integer status;

    public FashionstockHasUser() {
    }

	
    public FashionstockHasUser(Fashionstock fashionstock, User user) {
        this.fashionstock = fashionstock;
        this.user = user;
    }
    public FashionstockHasUser(Fashionstock fashionstock, User user, Date dateintake, Double qtyintake, Double suprate, Integer status) {
       this.fashionstock = fashionstock;
       this.user = user;
       this.dateintake = dateintake;
       this.qtyintake = qtyintake;
       this.suprate = suprate;
       this.status = status;
    }
   
    public Integer getFuelstockHasUserid() {
        return this.fuelstockHasUserid;
    }
    
    public void setFuelstockHasUserid(Integer fuelstockHasUserid) {
        this.fuelstockHasUserid = fuelstockHasUserid;
    }
    public Fashionstock getFashionstock() {
        return this.fashionstock;
    }
    
    public void setFashionstock(Fashionstock fashionstock) {
        this.fashionstock = fashionstock;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDateintake() {
        return this.dateintake;
    }
    
    public void setDateintake(Date dateintake) {
        this.dateintake = dateintake;
    }
    public Double getQtyintake() {
        return this.qtyintake;
    }
    
    public void setQtyintake(Double qtyintake) {
        this.qtyintake = qtyintake;
    }
    public Double getSuprate() {
        return this.suprate;
    }
    
    public void setSuprate(Double suprate) {
        this.suprate = suprate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


