package mypojos;
// Generated May 13, 2020 12:51:40 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fashionstock generated by hbm2java
 */
public class Fashionstock  implements java.io.Serializable {


     private Integer idfashion;
     private String itemName;
     private Double unitprice;
     private Double currentqty;
     private Integer status;
     private Set fashionstockHasUsers = new HashSet(0);
     private Set invoices = new HashSet(0);

    public Fashionstock() {
    }

    public Fashionstock(String itemName, Double unitprice, Double currentqty, Integer status, Set fashionstockHasUsers, Set invoices) {
       this.itemName = itemName;
       this.unitprice = unitprice;
       this.currentqty = currentqty;
       this.status = status;
       this.fashionstockHasUsers = fashionstockHasUsers;
       this.invoices = invoices;
    }
   
    public Integer getIdfashion() {
        return this.idfashion;
    }
    
    public void setIdfashion(Integer idfashion) {
        this.idfashion = idfashion;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }
    public Double getCurrentqty() {
        return this.currentqty;
    }
    
    public void setCurrentqty(Double currentqty) {
        this.currentqty = currentqty;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getFashionstockHasUsers() {
        return this.fashionstockHasUsers;
    }
    
    public void setFashionstockHasUsers(Set fashionstockHasUsers) {
        this.fashionstockHasUsers = fashionstockHasUsers;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


