package mypojos;
// Generated May 13, 2020 12:51:40 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceid;
     private Fashionstock fashionstock;
     private User user;
     private Double qtyintake;
     private Date dateintaken;
     private Double total;
     private Integer paytype;
     private Integer status;

    public Invoice() {
    }

	
    public Invoice(Fashionstock fashionstock, User user) {
        this.fashionstock = fashionstock;
        this.user = user;
    }
    public Invoice(Fashionstock fashionstock, User user, Double qtyintake, Date dateintaken, Double total, Integer paytype, Integer status) {
       this.fashionstock = fashionstock;
       this.user = user;
       this.qtyintake = qtyintake;
       this.dateintaken = dateintaken;
       this.total = total;
       this.paytype = paytype;
       this.status = status;
    }
   
    public Integer getInvoiceid() {
        return this.invoiceid;
    }
    
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }
    public Fashionstock getFashionstock() {
        return this.fashionstock;
    }
    
    public void setFashionstock(Fashionstock fashionstock) {
        this.fashionstock = fashionstock;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getQtyintake() {
        return this.qtyintake;
    }
    
    public void setQtyintake(Double qtyintake) {
        this.qtyintake = qtyintake;
    }
    public Date getDateintaken() {
        return this.dateintaken;
    }
    
    public void setDateintaken(Date dateintaken) {
        this.dateintaken = dateintaken;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


